# Site settings
title: Tomáš Hák
subtitle: personal website
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
url: "https://tomashak.github.io" # the base hostname & protocol for your site
# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

socials:
  GitHub: https://github.com/tomashak  
  LinkedIn: https://www.linkedin.com/in/haktom/
  Twitter: https://twitter.com/tomashak
  Facebook:
  Slack:

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
permalink: pretty

# Minimal Mistakes settings
minimal_mistakes_skin: "air"
header:
  image: "assets/images/header.jpg"