source "https://rubygems.org"

gem "jekyll", "~> 4.2"
gem "jekyll-theme-cayman"
gem "jekyll-feed"
gem "logger"
gem "csv"
gem "ostruct"
gem "base64"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-paginate"
gem "jekyll-archives"
gem "jekyll-redirect-from"
gem "jekyll-remote-theme"
gem "jekyll-include-cache"
gem "jekyll-optional-front-matter"
gem "jekyll-default-layout"
gem "jekyll-avatar"
gem "jekyll-mentions"